<template>
  <section class="ball-container">
    <img src="../assets/pokebola.png" class="pokeball" alt="" />
  </section>
</template>

<style scoped>
.ball-container {
  width: 50%;
  height: 100vh;
  margin: auto;
  display: flex;
  justify-content: center;
  align-items: center;
}

.pokeball {
  width: 150px;
  height: 150px;
  -webkit-animation: rotate-center 5s ease-in-out both;
  animation: rotate-center 5s ease-in-out both;
}

/* ----------------------------------------------
 * Generated by Animista on 2022-1-20 16:47:35
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation rotate-center
 * ----------------------------------------
 */
@-webkit-keyframes rotate-center {
  0% {
    -webkit-transform: rotate(0);
            transform: rotate(0);
  }
  100% {
    -webkit-transform: rotate(360deg);
            transform: rotate(360deg);
  }
}
@keyframes rotate-center {
  0% {
    -webkit-transform: rotate(0);
            transform: rotate(0);
  }
  100% {
    -webkit-transform: rotate(360deg);
            transform: rotate(360deg);
  }
}
</style>
